name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    cron: "0 0 * * 0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Request
      uses: fjogeleit/http-request-action@v1.12.0
      with:
        url: 'https://xhspicextractor-injectrl.cloud.okteto.net/'
        method: 'GET'
        preventFailureOnNoResponse: 'true'
        ignoreStatusCodes: '404,401,500,501'
